site_name: Teddy 的筆記本

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  language: 'zh-TW'
  features:
    - content.code.select
    - content.code.annotate
    - content.code.copy
    - toc.integrate
    - navigation.top

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Java:
    - Effective Java:
        - Item 01 - Consider static factory methods instead of constructors: java/effective-java/01_consider_static_factor_methods_instead_of_constructors.md
  - Spring Boot:
      - Scheduler:
        - Quartz:
          - Hello World!: spring-boot/scheduler/hello_world.md
          - JDBC JobStore: spring-boot/scheduler/jdbc_job_store.md
          # TODO: share data between jobs (via context ?)
          #       - Job vs Bean Job
          # TODO: tes

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      puml_keyword: plantuml
  - git-revision-date-localized:
      locale: zh
      enable_creation_date: true

copyright: Copyright &copy; 2024 Teddy Lee
extra:
  generator: false