site_name: Teddy 的筆記本

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  language: 'zh-TW'
  features:
    - content.code.select
    - content.code.annotate
    - content.code.copy
    - toc.integrate
    - navigation.top

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Spring Boot:
      - Scheduler:
        - Quartz:
          - Hello World!: spring-boot/scheduler/hello_world.md
          - JDBC JobStore: spring-boot/scheduler/jdbc_job_store.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      puml_keyword: plantuml

copyright: Copyright &copy; 2024 Teddy Lee
extra:
  generator: false