site_name: Teddy 的筆記本

use_directory_urls: false

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  language: 'zh-TW'
  features:
    - content.code.select
    - content.code.annotate
    - content.code.copy
    - toc.integrate
    - navigation.top

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - Blog: blog/index.md
  - IDE:
        - JetBrains 快捷鍵: ide/jet-brains/shortcuts.md
  - Java:
    - Effective Java, 3rd:
        - Creating And Destroying Objects:
          - Item 1 - Consider static factory methods instead of constructors: java/effective-java/001.md
          - Item 2 - Consider a builder when faced with many constructor parameters: java/effective-java/002.md
          - Item 3 - Enforce the singleton property with a private constructor or an enum type: java/effective-java/003.md
          - Item 4 - Enforce noninstantiability with a private constructor: java/effective-java/004.md
          - Item 5 - Prefer dependency injection to hardwiring resources: java/effective-java/005.md
          - Item 6 - Avoid creating unnecessary objects: java/effective-java/006.md
          - Item 7 - Eliminate obsolete object references: java/effective-java/007.md
          - Item 8 - Avoid finalizers and cleaners: java/effective-java/008.md
          - Item 9 - Prefer try-with-resources to try-finally: java/effective-java/009.md
        - Methods Common To All Objects:
          - Item 10 - Obey the general contract when overriding equals: java/effective-java/010.md
          - Item 11 - Always override hashCode when you override equals: java/effective-java/011.md
  - Spring Boot:
    - Scheduler:
      - Quartz:
        - Hello World!: spring-boot/scheduler/hello_world.md
        - JDBC JobStore: spring-boot/scheduler/jdbc_job_store.md
        # TODO: share data between jobs (via context ?)
        #       - Job vs Bean Job
        # TODO: tes
    - Testing: spring-boot/testing/index.md
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys

plugins:
  - search
  - blog
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      num_workers: 8
      puml_keyword: plantuml
  - git-revision-date-localized:
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - blog/**/*

copyright: Copyright &copy; 2024 Teddy Lee
extra:
  generator: false